### ISSUE TITLE
[Suggestion] Ajouter le chatbot sur d'autres plateformes de chat

### ISSUE THREAD

**Issue by GreepTheSheep** [hgueguen/alfred-messenger#2]
Pour les utilisateurs qui n'utilisent pas (ou plus) le chat Messenger, j'ai eu l'idée de "copier" le bot de rappel, pour le mettre vers d'autres plateformes.

Je vais fork le projet pour essayer de l'intégrer dans Discord, le souci c'est que j'y connais rien en Ruby et que mon préféré c'est le Node.JS, ça risque d'être un peu compliqué, mais je vais essayer ! Si t'as des tips, répond ici ;)

**Comment by Laiteux** [comment]
Déjà ici: https://github.com/hgueguen/alfred-messenger#to-dev-for-users

**Comment by GreepTheSheep** [comment]
oué tkt j'lai vu ça
